// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRdBtwP9Z6u8UjFvCpWq3MNkzRCQviS0M',
    appId: '1:1023410488328:web:478939792f1b63c1e53dbd',
    messagingSenderId: '1023410488328',
    projectId: 'flutter-todo-b6682',
    authDomain: 'flutter-todo-b6682.firebaseapp.com',
    storageBucket: 'flutter-todo-b6682.appspot.com',
    measurementId: 'G-17PNMWBH2N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOQ57wTQzTYF6C_TAivey3I_kt2PdVSpc',
    appId: '1:1023410488328:android:0541d334da426af8e53dbd',
    messagingSenderId: '1023410488328',
    projectId: 'flutter-todo-b6682',
    storageBucket: 'flutter-todo-b6682.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCySiQciExk7N0qjTN6RTujGdIypEXH1ZI',
    appId: '1:1023410488328:ios:af380c74d44391d1e53dbd',
    messagingSenderId: '1023410488328',
    projectId: 'flutter-todo-b6682',
    storageBucket: 'flutter-todo-b6682.appspot.com',
    iosClientId: '1023410488328-6j8qkbu04u5kegg8bhnc3u122bsnn70c.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCySiQciExk7N0qjTN6RTujGdIypEXH1ZI',
    appId: '1:1023410488328:ios:af380c74d44391d1e53dbd',
    messagingSenderId: '1023410488328',
    projectId: 'flutter-todo-b6682',
    storageBucket: 'flutter-todo-b6682.appspot.com',
    iosClientId: '1023410488328-6j8qkbu04u5kegg8bhnc3u122bsnn70c.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTodo',
  );
}
